apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app-status-monitor.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app-status-monitor.labels" . | nindent 4 }}
data:
  config.yaml: |
    watchInterval: {{ .Values.config.watchInterval }}
    
    defaultTimeouts:
      kafkatopic: 20m
      deployment: 10m