# templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app-status-monitor.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app-status-monitor.labels" . | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "app-status-monitor.fullname" . }}
  labels:
    {{- include "app-status-monitor.labels" . | nindent 4 }}
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["kafka.crossplane.io"]
  resources: ["kafkatopics"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["database.crossplane.io"]
  resources: ["postgresqlinstances"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["cache.crossplane.io"]
  resources: ["redisclusters"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "app-status-monitor.fullname" . }}
  labels:
    {{- include "app-status-monitor.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "app-status-monitor.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "app-status-monitor.fullname" . }}
  namespace: {{ .Values.namespace }}