apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app-status-monitor.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app-status-monitor.labels" . | nindent 4 }}